#-------------------------------------
# Task 4 Extra
#
# Integrate your docker image and your github repository. 
#
# Create an automatic deployment for each push.
#-------------------------------------

name: Docker_Publish

on:
  push:
    branches: [main]

jobs:

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker_files/extra
          push: true
          tags: uzcoder/extra_task:latest