#-------------------------------------
# Task 4 Extra
#
# Integrate your docker image and your github repository. 
#
# Create an automatic deployment for each push.
#-------------------------------------

name: Docker_Publish

on:
  push:
    branches: [main]

jobs:

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: uzcoder/extra_task
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    
